#+OPTIONS: num:nil toc:nil
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_PLUGINS: (highlight)
#+Title: React course
#+Author: Maxim Rurenko
#+Email: mrurenko@gmail.com

* Regulations
- 4 lessons: React + Redux
- 2+ hours of lecture and about 4 hours of practice
- Questions - anytime.
* Desired outcome
- Understand core concepts of React
- Comfortable to use React in your apps.
* React
- A JavaScript library for building user interfaces.
- Declarative
- Component-Based
- Learn Once, Write Anywhere
* Livecoding time
- Goal: To understand what I am doing. Have a question - please ask!
- Do not repeat what I am doing. Just follow and ask questions
- I will share a code if it is needed
* React
** Declarative
- React makes it painless to create interactive UIs.
- Design simple views for each state in your application, and React will efficiently
  update and render just the right components when your data changes.
- Declarative views make your code more predictable and easier to debug.
** Component-Based
- Build encapsulated components that manage their own state, then compose them to make complex UIs.
- Since component logic is written in JavaScript instead of templates,
  you can easily pass rich data through your app and keep state out of the DOM.
** Learn Once, Write Anywhere
- We don’t make assumptions about the rest of your technology stack,
  so you can develop new features in React without rewriting existing code.
- React can also render on the server using Node and power mobile apps using React Native.
* React Elements
- Elements are the smallest building blocks of React apps.
- React elements are immutable. Once you create an element,
  you can’t change its children or attributes.
  An element is like a single frame in a movie: it represents the UI at a certain point in time.
- React Only Updates What’s Necessary
- In our experience, thinking about how the UI should look at any given moment rather than how to change it over time eliminates a whole class of bugs.
* Components and Props
- Components let you split the UI into independent, reusable pieces, and think about each piece in isolation.
- The simplest way to define a component is to write a JavaScript function
- Don’t be afraid to split components into smaller components.
** Function and Class Components
- A function will be a valid React component if it accepts a single “props” object argument with data
  and returns a React element.
- Class components
** Composing Components
- Components can refer to other components in their output.
- This lets us use the same component abstraction for any level of detail.
** Props are Read-Only
- All React components must act like pure functions with respect to their props.
- Component must never modify its own props.
* About JSX
- JSX it is a syntax extension to JavaScript.
- We recommend using it with React to describe what the UI should look like.
- JSX may remind you of a template language, but it comes with the full power of JavaScript.
- React doesn’t require using JSX, but most people find it helpful as a visual aid when
  working with UI inside the JavaScript code.
- Babel compiles JSX down to React.createElement() calls.
** Embedding Expressions in JSX
- You can put any valid JavaScript expression inside the curly braces in JSX.
- For example, 2 + 2, user.firstName, or formatName(user) are all valid JavaScript expressions.
* State and Lifecycle
- Only class components have this
** Lifecycle Methods
- componentDidMount() method runs after the component output has been rendered to the DOM
- componentWillUnmount() method runs when the component going to be unmounted from DOM
** Using State Correctly
- Do Not Modify State Directly. Use setState()
- State Updates May Be Asynchronous
- State Updates are Merged
** The Data Flows Down
- Neither parent nor child components can know if a certain component is stateful or stateless,
  and they shouldn’t care whether it is defined as a function or a class.
- This is why state is often called local or encapsulated.
  It is not accessible to any component other than the one that owns and sets it.
- A component may choose to pass its state down as props to its child components.
* Handling Events
- Handling events with React elements is very similar to handling events on DOM elements.
- React events are named using camelCase, rather than lowercase
- With JSX you pass a function as the event handler, rather than a string
- Remeber to bind your event handlers to components 'this'.
* Conditional Rendering
- In React, you can create distinct components that encapsulate behavior you need.
- Then, you can render only some of them, depending on the state of your application.
** Element Variables
- You can use variables to store elements.
- This can help you conditionally render a part of the component while the rest of the output doesn’t change.
** Inline If with Logical && Operator
- You may embed any expressions in JSX by wrapping them in curly braces.
- This includes the JavaScript logical && operator.
** Inline If-Else with Conditional Operator
- Another method for conditionally rendering elements inline is to use the JavaScript
  conditional operator `condition ? true : false`
** Preventing Component from Rendering
- In rare cases you might want a component to hide itself even though it was rendered by another component.
- To do this return null instead of its render output.
* Lists and Keys
- A “key” is a special string attribute you need to include when creating lists of elements
- Keys help React identify which items have changed, are added, or are removed
- Keys should be given to the elements inside the array to give the elements a stable identity
- The best way to pick a key is to use a string that uniquely identifies a list item among its siblings
* Forms
- HTML form elements work a little bit differently from other DOM elements in React,
  because form elements naturally keep some internal state.
- This form has the default HTML form behavior of browsing to a new page when the user submits the form.
- If you want this behavior in React, it just works.
- But in most cases, it’s convenient to have a JavaScript function that handles the submission of
  the form and has access to the data that the user entered into the form.
** Controlled Components
- In HTML, form elements such as <input>, <textarea>, and <select> typically maintain their own state and update it based on user input.
- In React, mutable state is typically kept in the state property of components,
  and only updated with setState().
- We can combine the two by making the React state be the “single source of truth”.
- Then the React component that renders a form also controls what happens in that form on subsequent user input.
- An input form element whose value is controlled by React in this way is called a “controlled component”.
** Alternatives to Controlled Components
- Uncontrolled components
- this.input = React.createRef();
* Lifting State Up
- Often, several components need to reflect the same changing data.
- In React, sharing state is accomplished by moving it up to the closest common ancestor of the components that need it.
- This is called “lifting state up”.
- There should be a single “source of truth” for any data that changes in a React application.
* Composition vs Inheritance
- React has a powerful composition model, and we recommend using composition instead of inheritance
  to reuse code between components.
- At Facebook, they use React in thousands of components, and they haven’t found any use cases
  where we would recommend creating component inheritance hierarchies.
- Props and composition give you all the flexibility you need to customize a component’s look
  and behavior in an explicit and safe way.
- Remember that components may accept arbitrary props, including primitive values, React elements, or functions.
* Thinking in React
** Start With A Mock
** Step 1: Break The UI Into A Component Hierarchy
** Step 2: Build A Static Version in React
** Step 3: Identify The Minimal (but complete) Representation Of UI State
** Step 4: Identify Where Your State Should Live
** Step 5: Add Inverse Data Flow
* What to do next
- Setup React.
- Create base layout.
- Will share a basic layout
* Tools
- React DOM
- React Developer Tools
- React Router
- React
* Used resources
- React Docs: https://reactjs.org/docs/getting-started.html
